### ISSUE TITLE
Use static HTML instead of twirl

### ISSUE THREAD

**Issue by keddelzz** [morganey-lang/let-morganey-rest#1]
At the moment twirl is used to [generate the index-page](https://github.com/keddelzz/let-morganey-rest/blob/e432b80c8e81d1b00d4f2356cf71a9c22a093850/src/main/twirl/trymorganey/index.scala.html#L3) using Scala. Because the index-page is really simple, the generation of this page can be replaced by a static HTML page.

**Comment by keddelzz** [comment]
@rexim 
@kuchenkruste
What do you guys think?

**Comment by rexim** [comment]
I agree with that. The template doesn't even use any twirl features. :)
