### ISSUE TITLE
Initialize database on start of the service

### ISSUE THREAD

**Issue by keddelzz** [morganey-lang/let-morganey-rest#2]

**Comment by rexim** [comment]
Play Framework has so called Evolutions, which are used for DB scheme migration and initialization. They are pretty good, but I don't know if it's possible to use them separately like twirl. If not [Flyway](https://flywaydb.org/) is a pretty good choice.

**Comment by keddelzz** [comment]
An in memory database is used. It has a single database and also a single table. For now the initialization of the database is a single [sql query](https://github.com/keddelzz/let-morganey-rest/blob/9c16f0fb3025238fdde8e8eae7dec9c9d4ab92c7/src/main/scala/trymorganey/db/SessionSQLStatements.scala#L43). A framework for initialization might be too overkill at the moment, but thank you very much, I'll take a look at `Flyway`.
