### ISSUE TITLE
Describe REST-API

### ISSUE THREAD

**Issue by keddelzz** [morganey-lang/let-morganey-rest#25]
Describe REST calls and format of the json-messages in the README.

**Comment by rexim** [comment]
It would be cool to have swagger docs for let-morganey-rest. http://swagger.io/ But looks like that's outside of the scope of this issue.

What do you think? Do we need that? If so I can create a separate issue for that.

**Comment by keddelzz** [comment]
Although [swagger](http://swagger.io/) looks very professional, I think it might be too much for this project. 

We only have three routes, which could as well be described using markdown-tables.

**Comment by rexim** [comment]
Sounds reasonable. :)

**Comment by keddelzz** [comment]
If the API grows, [swagger](http://swagger.io/) might be a nice option!

**Comment by keddelzz** [comment]
An alternative to [swagger](http://swagger.io/) might be [slate](https://github.com/lord/slate).
