### ISSUE TITLE
Featuring let-morganey-rest on the community web-site

### ISSUE THREAD

**Issue by rexim** [morganey-lang/let-morganey-rest#26]
Derived from https://github.com/morganey-lang/morganey-lang.github.io/issues/3

We wanna feature let-morganey-rest on the community web-site https://morganey-lang.github.io/. For that we need:
- Deploy the let-morganey-rest backend somewhere. @ForNeVeR suggests Heroku in https://github.com/morganey-lang/morganey-lang.github.io/issues/3#issuecomment-253852760 and I second this, because we've been successfully using Heroku for our other pet projects.
- Decide what to do with the frontend part. Should it be duplicated in the site or completely transfered to the site?

@ForNeVeR @keddelzz @kuchenkruste what do you guys think?

**Comment by ForNeVeR** [comment]
Well, here's my vision of the situation.
1. Deploy let-morganey-rest somewhere at https://let-morganey-rest.herokuapp.com, for example.
2. Add an `<iframe>` pointing to this site at the https://morganey-lang.github.io/ page.

This way, we'll be able to present the whole Morganey toolbox at the one place (from user perspective), but won't need to copy any design or frontend part anywhere.

**Comment by rexim** [comment]
@ForNeVeR Do we have control over the style inside of an iframe. I wanna be able to change the style if needed without bothering let-morganey-rest guys.

**Comment by ForNeVeR** [comment]
> Do we have control over the style inside of an iframe.

Nope.

> I wanna be able to change the style if needed without bothering let-morganey-rest guys.

Well, I'm not very familiar with the internals of the project. Does it provide any (sort of) stable HTTP API? Probably we'll want to write another client (or extract _the_ client) as a library, and (re)use it at the Morganey site?

**Comment by rexim** [comment]
> Does it provide any (sort of) stable HTTP API? 

Yes. That's why it is called let-morganey-**rest** ;)

> Probably we'll want to write another client (or extract the client) as a library, and (re)use it at the Morganey site?

This is exactly what I was asking about in the description. I don't mind the idea of extracting the client as something reusable. Sounds pretty good for me.

**Comment by rexim** [comment]
@keddelzz, sorry for bothering you, but since you're the Project Leader of this project (see [Project.md](https://github.com/morganey-lang/community/blob/88afde8d87b72036ed5077be431a48ebe7f9c63d/Projects.md#let-morganey-rest)) and according to our rules "Project Leaders are responsible for organizing the development process of the projects they lead" (see [README.md](https://github.com/morganey-lang/community/blob/88afde8d87b72036ed5077be431a48ebe7f9c63d/README.md#becoming-a-project-leader)) I was expecting your action here.

**Do you accept the idea of extracting the client part?**

If you don't have time on our silly development process games I can help you here. :) I'll create all of the required issues and pull request that will lead to embedding let-morganey-rest into morganey-lang site. The only thing will be required from you is to accept or reject things I propose. I'll try to make them as small scoped as possible so you don't waste much time on reviewing them. Sounds good?

**Comment by keddelzz** [comment]
> Do you accept the idea of extracting the client part?

Yes! I like the idea of extracting the client part. So of course I accept it!

**Comment by rexim** [comment]
So I guess the scope of this proposal is exhausted. Hence closing.
